apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth-server
    spec:
      containers:
      - image: timothymehay/auth-server
        name: auth-server
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: auth-server
  name: auth-server
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: auth-server
  type: ClusterIP
status:
  loadBalancer: {}
